back:
  mode: 'back'
  image_path: './image/test.jpg'
  output_path: './output/output_back.png'
  is_save: True
  translate:
    tx: 30
    ty: 30
  rotate:
    degree: 15
  scaling:
    sx: 2
    sy: 2
  affine:
    tx: 30
    ty: 30
    degree: 132
    sx: 1.3
    sy: 1.3
  

base:
  mode: 'base'
  image_path: './image/test.jpg'
  output_path: './output/output_base.png'
  is_save: True  
  translate:
    tx: 30
    ty: 30
  rotate:
    degree: 15
  scaling:
    sx: 2
    sy: 2
  affine:
    tx: 30
    ty: 30
    degree: 132
    sx: 1.3
    sy: 1.3